# This is a basic workflow that is manually triggered

name: Smoke Tests -Chrome

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main
    pull_request:
      types: [ opened, synchronize, reopened ]
permissions:
  contents: write
  id-token: write
  checks: write

jobs:
  test:
    name: Smoke tests
    #runs-on: windows-latest
    runs-on: ubuntu-latest
    env:
      RUNNER_OS: true
      HEADLESS_CHROME: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: 18
          distribution: 'temurin'
          cache: maven
      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@latest
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run tests with Maven
        run: xvfb-run mvn -DfailIfNoTests=false -Dtest=SmokeTest --file pom.xml test -q
        env:
          DISPLAY: 19
          CUCUMBER_PUBLISH_TOKEN:
      - name: Store artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./test-reports/
      - name: Test Reporter
        if: always()
        uses: dorny/test-reporter@v1.6.0
        with:
          name: Test Report
          path: "**/surefire-reports/TEST-SmokeTest.xml"
          reporter: java-junit
#          token: ${{ secrets.GITHUB_TOKEN }}
#      - name: Slack Notification
#        if: always()
#        uses: rtCamp/action-slack-notify@v2
#        env:
#          SLACK_CHANNEL: smoke-test-report
#          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
#          SLACK_ICON: https://github.com/rtCamp.png?size=48
#          SLACK_MESSAGE:
#          SLACK_TITLE: Cucumber Test Report ':rocket:'
#          SLACK_USERNAME: rtCamp
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
